#!/usr/bin/python
# -*- coding: utf-8 -*-


import csv
import codecs

def read_csv(filepath):
    results = []
    reader = csv.reader(file(filepath, 'rU'))
    for line in reader:
        results.append(line)
    return results

def write_csv(filepath,llist):
    writer = csv.writer(file(filepath, 'wb'))
    for line in llist:
        writer.writerow(line)



def read_ontology(filepath):
    result = []
    file_obj = codecs.open(filepath,'r','utf-8')
    while True:
        line = file_obj.readline()
        if 'Generated by the OWL API' in line:
            result.append(line)
            break
        result.append(line)
    file_obj.close()
    return result

def write_ontology(filepath,lines):
    file_object = open(filepath,'w')
    for line in lines:
        file_object.write(line)
    file_object.close()